use_frameworks!

platform :ios, '8.0'

target 'BlueTriangleSDK_Example' do
  pod 'BlueTriangleSDK', :path => '../'

  target 'BlueTriangleSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
